name: Build TaikoMini APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up Java and Android SDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y android-sdk
        export ANDROID_HOME=/usr/lib/android-sdk
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-34" "build-tools;34.0.0"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Decode Keystore
      env:
        KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}
      run: |
        echo $KEYSTORE_B64 | base64 --decode > release.keystore

    - name: Build with Buildozer
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}
      run: |
        sed -i "s|^android.release_key_store =.*|android.release_key_store = release.keystore|" buildozer.spec
        sed -i "s|^android.release_key_store_password =.*|android.release_key_store_password = $KEYSTORE_PASSWORD|" buildozer.spec
        sed -i "s|^android.release_key_alias =.*|android.release_key_alias = $KEY_ALIAS|" buildozer.spec
        sed -i "s|^android.release_key_alias_password =.*|android.release_key_alias_password = $KEY_ALIAS_PASSWORD|" buildozer.spec
        buildozer android release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: taikomini-release
        path: bin/*.apk
